export enum ReportTypes {
    NO_SHOW = "NO_SHOW",
    LATE_ARRIVAL = "LATE_ARRIVAL",
    RUDE_BEHAVIOR = "RUDE_BEHAVIOR",
    UNSAFE_DRIVING = "UNSAFE_DRIVING",
    PAYMENT_ISSUES = "PAYMENT_ISSUES",
    ROUTE_CHANGE = "ROUTE_CHANGE",
    UNAPPROVED_STOPS = "UNAPPROVED_STOPS",
    SUBSTANCE_USE = "SUBSTANCE_USE"
}